// src/theme/styles.ts

import { Platform, StyleSheet } from 'react-native';
import Constants from 'expo-constants';

const FONT_FAMILY = Platform.select({
    ios: 'System',
    android: 'Roboto',
    default: 'sans-serif',
});

export const COLORS = {
    primary: '#f97316',
    primaryDark: '#c2410c',
    primaryLight: '#ffedd5',
    secondary: '#94a3b8',
    danger: '#ef4444',
    warning: '#f59e0b',
    background: '#f8fafc',
    white: '#ffffff',
    textDark: '#0f172a',
    textMuted: '#64748b',
    border: '#cbd5e1',
    chipBg: '#f1f5f9',
    placeholder: '#94a3b8',
};

export const SCREEN_BOTTOM_SPACING = 40;

export const styles = StyleSheet.create({
    flex1: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    headerContainer: {
        height: 100,
        paddingTop: Constants.statusBarHeight,
        backgroundColor: COLORS.primary,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        color: COLORS.white,
        fontSize: 22,
        fontWeight: 'bold',
        marginHorizontal: 15,
        fontFamily: FONT_FAMILY,
    },
    formPadding: {
        padding: 20,
    },
    formScrollContent: {
        paddingBottom: SCREEN_BOTTOM_SPACING,
    },
    label: {
        fontWeight: 'bold',
        color: COLORS.textDark,
        marginTop: 10,
        marginBottom: 5,
        fontFamily: FONT_FAMILY,
    },
    input: {
        backgroundColor: COLORS.white,
        padding: 12,
        borderRadius: 15,
        borderWidth: 1,
        borderColor: COLORS.border,
        marginBottom: 15,
        fontSize: 16,
        color: COLORS.textDark,
        fontFamily: FONT_FAMILY,
    },
    mainButton: {
        padding: 15,
        borderRadius: 20,
        alignItems: 'center',
        elevation: 2,
        marginTop: 10,
        backgroundColor: COLORS.primary,
    },
    buttonText: {
        color: COLORS.white,
        fontWeight: 'bold',
        fontSize: 16,
        fontFamily: FONT_FAMILY,
    },
    chipGroup: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginVertical: 6,
    },
    queryButtonRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginBottom: 12,
    },
    chip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.chipBg,
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    chipSelected: {
        backgroundColor: COLORS.primary,
        borderColor: COLORS.primaryDark,
    },
    chipText: {
        fontSize: 14,
        color: COLORS.textDark,
        fontWeight: '500',
        fontFamily: FONT_FAMILY,
    },
    chipTextSelected: {
        color: COLORS.white,
        fontWeight: 'bold',
        fontFamily: FONT_FAMILY,
    },
    clearButton: {
        backgroundColor: COLORS.white,
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: COLORS.danger,
    },
    clearButtonText: {
        fontSize: 14,
        color: COLORS.danger,
        fontWeight: 'bold',
        fontFamily: FONT_FAMILY,
    },
    tabBar: {
        flexDirection: 'row',
        height: 65,
        backgroundColor: COLORS.white,
        borderTopWidth: 1,
        borderTopColor: COLORS.border,
    },
    tabItem: {
        flex: 1,
        justifyContent: 'center',
        flexDirection: 'row',
        alignItems: 'center',
    },
    tabActive: {
        borderTopWidth: 3,
        borderTopColor: COLORS.primary,
    },
    tabText: {
        color: COLORS.textMuted,
        fontWeight: '600',
        fontFamily: FONT_FAMILY,
    },
    tabTextActive: {
        color: COLORS.primary,
        fontWeight: 'bold',
        fontFamily: FONT_FAMILY,
    },
    listContainer: {
        flex: 1,
        padding: 15,
        paddingBottom: SCREEN_BOTTOM_SPACING,
    },
    controlContainer: {
        backgroundColor: COLORS.white,
        padding: 12,
        borderRadius: 15,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    controlLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: COLORS.textDark,
        marginBottom: 8,
        textAlign: 'center',
        fontFamily: FONT_FAMILY,
    },
    buttonGroup: {
        flexDirection: 'row',
        justifyContent: 'space-around',
    },
    dayButton: {
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 12,
        backgroundColor: COLORS.chipBg,
    },
    dayButtonActive: {
        backgroundColor: COLORS.primary,
    },
    dayButtonText: {
        fontSize: 13,
        color: COLORS.textDark,
        fontWeight: '500',
        fontFamily: FONT_FAMILY,
    },
    dayButtonTextActive: {
        color: COLORS.white,
        fontWeight: 'bold',
        fontFamily: FONT_FAMILY,
    },
    emptyContainer: {
        marginTop: 40,
        alignItems: 'center',
    },
    emptyText: {
        color: COLORS.textMuted,
        fontSize: 15,
        fontFamily: FONT_FAMILY,
    },
    card: {
        backgroundColor: COLORS.white,
        padding: 15,
        marginHorizontal: 15,
        marginVertical: 6,
        borderRadius: 20,
        elevation: 2,
        borderLeftWidth: 6,
        borderLeftColor: COLORS.primary,
    },
    cardRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 5,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginLeft: 10,
        color: COLORS.textDark,
        fontFamily: FONT_FAMILY,
    },
    cardExp: {
        color: COLORS.danger,
        fontWeight: 'bold',
        marginTop: 5,
        fontFamily: FONT_FAMILY,
    },
    cardLoc: {
        color: COLORS.textMuted,
        fontSize: 13,
        marginTop: 2,
        fontFamily: FONT_FAMILY,
    },
    sectionTitle: {
        textAlign: 'center',
        fontWeight: 'bold',
        color: COLORS.textMuted,
        marginTop: 10,
        marginBottom: 10,
        fontFamily: FONT_FAMILY,
    },
    backButtonContainer: {
        width: '100%',
        minHeight: 90,
        paddingTop: 40,
        paddingHorizontal: 16,
        paddingBottom: 12,
        backgroundColor: COLORS.primary,
        flexDirection: 'row',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: COLORS.primaryDark,
    },
    backButtonIcon: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(255, 255, 255, 0.25)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    backButtonTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: COLORS.white,
        fontFamily: FONT_FAMILY,
    },
    addScreenSuccessContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 28,
    },
    addScreenSuccessIcon: {
        width: 96,
        height: 96,
        borderRadius: 48,
        backgroundColor: COLORS.primaryLight,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    },
    addScreenSuccessTitle: {
        fontSize: 26,
        fontWeight: '700',
        color: COLORS.textDark,
        marginBottom: 8,
        fontFamily: FONT_FAMILY,
    },
    addScreenSuccessDescription: {
        fontSize: 15,
        color: COLORS.textMuted,
        textAlign: 'center',
        marginBottom: 24,
        fontFamily: FONT_FAMILY,
    },
    addScreenContinueButton: {
        backgroundColor: COLORS.primary,
        borderRadius: 18,
        paddingVertical: 14,
        paddingHorizontal: 28,
        width: '100%',
        alignItems: 'center',
    },
    addScreenContinueButtonText: {
        color: COLORS.white,
        fontWeight: '700',
        fontSize: 16,
        fontFamily: FONT_FAMILY,
    },
    addScreenScanBarcodeWrapper: {
        paddingHorizontal: 16,
        marginTop: 8,
    },
    addScreenScanBarcodeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#f97316',
        borderWidth: 1,
        borderColor: '#ea580c',
        borderRadius: 8,
        paddingVertical: 12,
        paddingHorizontal: 16,
        gap: 8,
    },
    addScreenScanBarcodeText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#ffffff',
        fontFamily: FONT_FAMILY,
    },
    groceryCardActionsRow: {
        flexDirection: 'row',
        gap: 10,
        marginTop: 12,
    },
    groceryBuyButton: {
        flex: 1,
        backgroundColor: COLORS.primary,
        borderRadius: 12,
        paddingVertical: 10,
        alignItems: 'center',
    },
    groceryBuyText: {
        color: '#ffffff',
        fontWeight: '700',
        fontFamily: FONT_FAMILY,
    },
    groceryRemoveButton: {
        flex: 1,
        backgroundColor: '#ef4444',
        borderRadius: 12,
        paddingVertical: 10,
        alignItems: 'center',
    },
    groceryRemoveText: {
        color: '#ffffff',
        fontWeight: '700',
        fontFamily: FONT_FAMILY,
    },
    ingredientDeleteText: {
        color: '#ef4444',
        fontWeight: '700',
        fontFamily: FONT_FAMILY,
    },
    ingredientStatusRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 8,
    },
    ingredientStatusTag: {
        backgroundColor: COLORS.primaryLight,
        borderRadius: 999,
        paddingHorizontal: 8,
        paddingVertical: 4,
        marginRight: 6,
    },
    formHelperText: {
        fontSize: 12,
        color: '#64748b',
        marginTop: 4,
        marginBottom: 8,
        fontFamily: FONT_FAMILY,
    },
    ripenessSection: {
        marginTop: 8,
        marginBottom: 12,
    },
    ripenessTrackFrame: {
        position: 'relative',
        paddingVertical: 8,
    },
    ripenessTrack: {
        height: 8,
        borderRadius: 999,
        backgroundColor: '#e2e8f0',
        overflow: 'hidden',
    },
    ripenessTrackOverlay: {
        position: 'absolute',
        left: 0,
        right: 0,
        top: 8,
        height: 8,
        borderRadius: 999,
        backgroundColor: 'transparent',
        borderWidth: 0,
    },
    ripenessFill: {
        position: 'absolute',
        left: 0,
        top: 8,
        height: 8,
        borderRadius: 999,
        opacity: 1,
    },
    ripenessOptionsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 12,
    },
    ripenessOption: {
        flex: 1,
        alignItems: 'center',
    },
    ripenessDot: {
        width: 14,
        height: 14,
        borderRadius: 999,
        borderWidth: 2,
        marginBottom: 8,
    },
    ripenessDotSelected: {
        borderWidth: 2,
    },
    ripenessDotText: {
        fontSize: 10,
        textAlign: 'center',
    },
    formSwitchGroup: {
        marginVertical: 12,
        gap: 16,
    },
    formSwitchRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    formSwitchContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        flex: 1,
        paddingRight: 8,
    },
    formSwitchDescription: {
        fontSize: 11,
        color: '#64748b',
        marginTop: 2,
        fontFamily: FONT_FAMILY,
    },
});