import { Platform, StyleSheet } from 'react-native';
import Constants from 'expo-constants';

const FONT_FAMILY = Platform.select({
    ios: 'System',
    android: 'Roboto',
    default: 'System',
});

const baseButton = {
    padding: 15,
    borderRadius: 20,
    alignItems: 'center',
    elevation: 2,
    marginTop: 10,
};

export const COLORS = {
    primary: '#f97316',
    primaryDark: '#c2410c',
    primaryLight: '#ffedd5',
    primaryGradient: ['#fd6900', '#f5840b'],
    secondary: '#94a3b8',
    danger: '#ef4444',
    warning: '#f59e0b',
    background: '#f8fafc',
    white: '#ffffff',
    textDark: '#0f172a',
    textMuted: '#64748b',
    border: '#cbd5e1',
    chipBg: '#f1f5f9',
    placeholder: '#94a3b8',
};

export const SCREEN_BOTTOM_SPACING = 40;

export const styles = StyleSheet.create({
    flex1: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    headerContainer: {
        height: 120,
        paddingTop: Constants.statusBarHeight,
        backgroundColor: COLORS.primary,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    },
    headerTitle: {
        color: COLORS.white,
        fontSize: 25,
        fontWeight: 'bold',
        marginHorizontal: 3,
        fontFamily: FONT_FAMILY,
    },
    headerSubtitle: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: 500,
    marginTop: 5,
    textAlign: 'center',
    },
    formPadding: {
        padding: 20
    },
    formScrollContent: {
        paddingBottom: SCREEN_BOTTOM_SPACING,
    },
    label: {
        fontWeight: 'bold',
        color: COLORS.textDark,
        marginTop: 10,
        marginBottom: 10,
        marginLeft: 5,
        fontFamily: FONT_FAMILY,
    },
    switchRowTitle: {
    fontWeight: 'bold',
    color: COLORS.textDark,
    fontFamily: FONT_FAMILY,
    },
    input: {
        backgroundColor: COLORS.white,
        padding: 12,
        borderRadius: 15,
        borderWidth: 1,
        borderColor: COLORS.border,
        marginBottom: 15,
        fontSize: 16,
        color: COLORS.textDark,
        fontFamily: FONT_FAMILY,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    container: {
        flex: 1,
        backgroundColor: '#0f172a',
    },
    cameraContainer: {
        flex: 1,
    },
    permissionContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 24,
        backgroundColor: '#f8fafc',
    },
    permissionText: {
        fontSize: 16,
        textAlign: 'center',
        marginBottom: 20,
        color: '#0f172a',
    },
    fallbackButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#e2e8f0',
        borderRadius: 8,
        paddingVertical: 10,
        paddingHorizontal: 16,
        gap: 6,
    },
    fallbackButtonText: {
        color: '#0f172a',
        fontWeight: '600',
    },
    tabBar: {
        height: 76,
        backgroundColor: '#ffffff',
        borderTopWidth: 0,
        borderRadius: 26,
        marginHorizontal: 14,
        marginBottom: 10,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.10,
        shadowRadius: 14,
        elevation: 8,
        paddingTop: 8,
        paddingBottom: 8,
    },
    tabBarItem: {
        borderRadius: 18,
        marginHorizontal: 4,
        height: 54,
    },
    tabBarLabel: {
        fontWeight: '600',
        fontSize: 11,
        marginTop: 2,
    },
    mainButton: {
        ...baseButton,
        backgroundColor: COLORS.primary,
    },
    cancelButton: {
        ...baseButton,
        backgroundColor: '#94a3b8',
    },
    deleteButton: {
        ...baseButton,
        backgroundColor: COLORS.danger,
    },
    buttonText: {
        color: COLORS.white,
        fontWeight: 'bold',
        fontSize: 16,
        fontFamily: FONT_FAMILY,
    },
    chipGroup: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginVertical: 6,
    },
    queryButtonRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginBottom: 4,
    },
    chip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: COLORS.chipBg,
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    chipSelected: {
        backgroundColor: COLORS.primary,
        borderColor: COLORS.primaryDark,
    },
    chipText: {
        fontSize: 14,
        color: COLORS.textDark,
        fontWeight: '500',
        fontFamily: FONT_FAMILY,
    },
    chipTextSelected: {
        color: COLORS.white,
        fontWeight: 'bold',
        fontFamily: FONT_FAMILY,
    },
    clearButton: {
        backgroundColor: COLORS.white,
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: COLORS.danger,
    },
    clearButtonText: {
        fontSize: 14,
        color: COLORS.danger,
        fontWeight: 'bold',
        fontFamily: FONT_FAMILY,
    },
    tabItem: {
        flex: 1,
        justifyContent: 'center',
        flexDirection: 'row',
        alignItems: 'center',
    },
    tabActive: {
        borderTopWidth: 3,
        borderTopColor: COLORS.primary,
    },
    tabText: {
        color: COLORS.textMuted,
        fontWeight: '600',
        fontFamily: FONT_FAMILY,
    },
    tabTextActive: {
        color: COLORS.primary,
        fontWeight: 'bold',
        fontFamily: FONT_FAMILY,
    },
    listContainer: {
        flex: 1,
        padding: 15,
        paddingBottom: SCREEN_BOTTOM_SPACING,
    },
    flatListContent: {
    paddingHorizontal: 8,   
    paddingTop: 15,
    paddingBottom: SCREEN_BOTTOM_SPACING,
},
    controlContainer: {
        backgroundColor: COLORS.white,
        padding: 12,
        borderRadius: 15,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    controlLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: COLORS.textDark,
        marginBottom: 8,
        textAlign: 'center',
        fontFamily: FONT_FAMILY,
    },
    shopContainer: {
        backgroundColor: COLORS.primary,
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 14,
        marginBottom: 4,
        borderWidth: 1,
        borderColor: '#ffedd5',
        flexDirection: 'row',
        alignItems: 'center',
    },
    shopLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: COLORS.white,
        fontFamily: FONT_FAMILY,
        marginLeft: 8,
        flex: 1,
    },
    buttonGroup: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '100%',
        gap: 8,
        marginTop: 8,
    },
    specialButton: {
        flex: 1,
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 20,
        backgroundColor: COLORS.chipBg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    specialButtonActive: {
        backgroundColor: COLORS.primary,
    },
    specialButtonText: {
        fontSize: 14,
        color: COLORS.textDark,
        fontWeight: '500',
        fontFamily: FONT_FAMILY,
        textAlign: 'center',
    },
    specialButtonTextActive: {
        color: COLORS.white,
        fontWeight: '700',
        fontFamily: FONT_FAMILY,
    },
    quantityContainer: {
        flexDirection: 'row', 
        alignItems: 'center', 
        gap: 8,
        marginBottom: -15,
    },
    emptyContainer: {
        marginTop: 40,
        alignItems: 'center',
    },
    emptyText: {
        color: COLORS.textMuted,
        fontSize: 15,
        marginLeft: 5,
        fontFamily: FONT_FAMILY,
    },
    card: {
        backgroundColor: COLORS.white,
        padding: 15,
        marginVertical: 6,
        marginHorizontal: 4,   
        borderRadius: 20,
        elevation: 2,
        borderLeftWidth: 6,
        borderLeftColor: COLORS.primary,
    },
    cardRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 5,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: COLORS.textDark,
        fontFamily: FONT_FAMILY,
        flexShrink: 1,
    },
    cardExp: {
        color: COLORS.danger,
        fontWeight: 'bold',
        marginTop: 5,
        fontFamily: FONT_FAMILY,
    },
    cardLoc: {
        color: COLORS.textMuted,
        fontSize: 13,
        marginTop: 2,
        fontFamily: FONT_FAMILY,
    },
    frozenCard: {
        backgroundColor: '#e3f4ff',
        borderLeftColor: '#0284c7',
    },
    sectionTitle: {
        textAlign: 'center',
        fontWeight: 'bold',
        color: COLORS.textMuted,
        marginTop: 10,
        marginBottom: 10,
        fontFamily: FONT_FAMILY,
    },
    backButtonContainer: {
        width: '100%',
        minHeight: 90,
        paddingTop: 40,
        paddingHorizontal: 16,
        paddingBottom: 12,
        backgroundColor: COLORS.primary,
        flexDirection: 'row',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: COLORS.primaryDark,
    },
    backButtonIcon: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(255, 255, 255, 0.25)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    backButtonTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: COLORS.white,
        fontFamily: FONT_FAMILY,
    },
    addScreenSuccessContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 28,
    },
    addScreenSuccessIcon: {
        width: 96,
        height: 96,
        borderRadius: 48,
        backgroundColor: COLORS.primaryLight,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    },
    addScreenSuccessTitle: {
        fontSize: 26,
        fontWeight: '700',
        color: COLORS.textDark,
        marginBottom: 8,
        fontFamily: FONT_FAMILY,
    },
    addScreenSuccessDescription: {
        fontSize: 15,
        color: COLORS.textMuted,
        textAlign: 'center',
        marginBottom: 24,
        fontFamily: FONT_FAMILY,
    },
    addScreenContinueButton: {
        backgroundColor: COLORS.primary,
        borderRadius: 18,
        paddingVertical: 14,
        paddingHorizontal: 28,
        width: '100%',
        alignItems: 'center',
    },
    addScreenContinueButtonText: {
        color: COLORS.white,
        fontWeight: '700',
        fontSize: 16,
        fontFamily: FONT_FAMILY,
    },
    addScreenScanBarcodeWrapper: {
        paddingHorizontal: 16,
        marginTop: 8,
    },
    addScreenScanBarcodeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.primary,
        borderWidth: 2,
        borderColor:'rgba(255, 255, 255, 0.4)',
        borderRadius: 14,
        paddingVertical: 14,
        paddingHorizontal: 16,
        gap: 8,
        elevation: 3,              
        shadowColor: '#000',        
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
    },
    addScreenScanBarcodeText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#ffffff',
        fontFamily: FONT_FAMILY,
    },
    quickAddRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 4,
    },
    quickAddInput: {
        flex: 1,
        marginRight: 10,
        marginBottom: 0,
    },
    quickAddButton: {
        backgroundColor: COLORS.primary,
        borderRadius: 12,
        paddingHorizontal: 20,
        justifyContent: 'center',
        alignItems: 'center',
        height: 48,
    },
    groceryCardActionsRow: {
        flexDirection: 'row',
        gap: 10,
        marginTop: 12,
    },
    groceryBuyButton: {
        flex: 1,
        backgroundColor: COLORS.primary,
        borderRadius: 12,
        paddingVertical: 10,
        alignItems: 'center',
    },
    groceryBuyText: {
        color: '#ffffff',
        fontWeight: '700',
        fontFamily: FONT_FAMILY,
    },
    groceryRemoveButton: {
        flex: 1,
        backgroundColor: '#ef4444',
        borderRadius: 12,
        paddingVertical: 10,
        alignItems: 'center',
    },
    groceryRemoveText: {
        color: '#ffffff',
        fontWeight: '700',
        fontFamily: FONT_FAMILY,
    },
    ingredientDeleteText: {
        color: '#ef4444',
        fontWeight: '700',
        fontFamily: FONT_FAMILY,
    },
    ingredientStatusRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 8,
    },
    ingredientStatusTag: {
        backgroundColor: COLORS.primaryLight,
        borderRadius: 999,
        paddingHorizontal: 8,
        paddingVertical: 4,
        marginRight: 6,
    },
    formHelperRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 6,
        marginBottom: 8,
    },
    formHelperText: {
        fontSize: 13,
        color: '#64748b',
        marginLeft: 6,
        fontFamily: FONT_FAMILY,
    },
    ripenessSection: {
        marginTop: 8,
        marginBottom: 12,
    },
    ripenessTrackFrame: {
        position: 'relative',
        paddingVertical: 8,
    },
    ripenessTrack: {
        height: 8,
        borderRadius: 999,
        backgroundColor: '#e2e8f0',
        overflow: 'hidden',
    },
    ripenessTrackOverlay: {
        position: 'absolute',
        left: 0,
        right: 0,
        top: 8,
        height: 8,
        borderRadius: 999,
        backgroundColor: 'transparent',
        borderWidth: 0,
    },
    ripenessFill: {
        position: 'absolute',
        left: 0,
        top: 8,
        height: 8,
        borderRadius: 999,
        opacity: 1,
    },
    ripenessOptionsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 12,
    },
    ripenessOption: {
        flex: 1,
        alignItems: 'center',
    },
    ripenessDot: {
        width: 14,
        height: 14,
        borderRadius: 999,
        borderWidth: 2,
        marginBottom: 8,
    },
    ripenessDotSelected: {
        borderWidth: 2,
    },
    ripenessDotText: {
        fontSize: 10,
        textAlign: 'center',
    },
    dietaryBox: {
    backgroundColor: COLORS.white,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginBottom: 15,
    },
    dietaryRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 10,
        gap: 10,
    },
    checkbox: {
        width: 20,
        height: 20,
        borderRadius: 5,
        borderWidth: 2,
        borderColor: COLORS.border,
        justifyContent: 'center',
        alignItems: 'center',
    },
    checkboxChecked: {
        backgroundColor: COLORS.primary,
        borderColor: COLORS.primary,
    },
    dietaryLabel: {
        fontSize: 15,
        color: COLORS.textDark,
        fontFamily: FONT_FAMILY,
    },  
    formSwitchGroup: {
        marginVertical: 12,
    },
    formSwitchRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        flex: 1,
    },  
    formSwitchContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        flex: 1,
        paddingRight: 8,
    },
    formSwitchDescription: {
        fontSize: 11,
        color: '#64748b',
        marginTop: 2,
        fontFamily: FONT_FAMILY,
        flexShrink: 1,
    },
    formFieldsDistance: {
        marginBottom: -10,
    },
    cardFooterRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 8,
        alignItems: 'flex-end',
        gap: 8,
    },
    missingDetailsBadge: {
        backgroundColor: '#fffbeb',
        borderColor: COLORS.warning,
        borderWidth: 1,
        height: 20,
        borderRadius: 10,
        width: 108, 
        alignItems: 'center',
        justifyContent: 'center',
    },
    missingDetailsText: {
        color: COLORS.warning,
        fontSize: 11,
        fontWeight: '700',
        textAlign: 'center',
    },
    ripenessBadge: {
        backgroundColor: '#fed5d5ea',        
        borderColor: '#d90606',            
        borderWidth: 1,
        height: 20,
        borderRadius: 10,
        width: 108, 
        alignItems: 'center',
        justifyContent: 'center',
    },
    ripenessText: {
        color: '#d90606',                  
        fontSize: 11,
        fontWeight: '700',
        textAlign: 'center',
    },
    badgesColumn: {
        flexDirection: 'column',
        alignItems: 'flex-end',
        gap: 6, 
    },
});